# Generated by Django 4.2.14 on 2024-08-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_master',
            name='category',
            field=models.CharField(choices=[('ews', 'EWS'), ('obc', 'OBC'), ('general', 'General'), ('sc', 'SC')], default='general', max_length=7),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('passedout', 'Passed Out')], default='current', max_length=10),
        ),
    ]
