# Generated by Django 4.2.14 on 2024-08-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_master_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_master',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
