# Generated by Django 4.2.14 on 2024-08-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_student_master_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_master',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
