# Generated by Django 4.2.14 on 2024-08-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_student_master_bus_id_student_master_bus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_master',
            old_name='bus',
            new_name='bus_id',
        ),
    ]
