# Generated by Django 4.2.14 on 2024-08-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_student_class_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_class',
            name='student_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to='app.student_master'),
        ),
    ]
