# Generated by Django 4.2.14 on 2024-08-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_student_class_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_class',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
