# Generated by Django 4.2.14 on 2024-08-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_student_class_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_class',
            name='section',
            field=models.CharField(choices=[('', 'Select the Section'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='concession_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
