# Generated by Django 4.2.14 on 2024-08-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_student_class_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_master',
            name='concession_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
