# Generated by Django 4.2.14 on 2024-08-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_student_master_concession_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busfees_master',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
