# Generated by Django 4.2.14 on 2024-08-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_busfees_master_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_master',
            name='addmission_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student_master',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
