# Generated by Django 4.2.14 on 2024-08-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_fees_master_class_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees_master',
            name='security_fees',
            field=models.IntegerField(default=0),
        ),
    ]
